sceneids: ["/Users/charlie/Projects/Holodeck/hippo/sampled_scenes/tunedparams/TRELLIS-yes-mask_True-axis-90_2025-08-08-12-55-40/random_0/scene.json"]
tasks: [["Make a tower green on dark on red."]]
robots: null