wall_height: 3
pad: 3
remove_obj_name_substr: ["interlocking mat"]  # removes any CG obj that contains any of the substrings in filter_obs
remove_obj_desc_substr: [""]
statistical_pcd_denoise_std: 0.05
floor_material:  "PVCLit"
wall_material: "EggshellDrywall"
topdown_camera_y: "bounds_y"


num_scenes_to_generate: 1
scene_generation_method: "random"