scene_id: "replica_room0_cg-detector_2025-06-10-20-16-50.243828"

conceptgraphs_dir: "./datasets/fullreplica"
scene_dir: "${paths.conceptgraphs_dir}/${paths.scene_id}"

out_subdir: "replica_room0_banner"
out_dir: "./sampled_scenes"
out_scene_dir: "${paths.out_dir}/${paths.out_subdir}/${paths.scene_id}/generated_on_${now:%Y-%m-%d-%H-%M-%S}"
