
defaults:
  - meta: meta
  - assetlookup: trellis
  - skillprediction: gpt4
  - paths: default
  - secrets: secrets
  - assetfitting: rot_and_aspect_weighted
  - scene: all_replica_scenes
  - parallelism: default