
defaults:
  - meta: meta
  - assetlookup: clip
  - skillprediction: none
  - paths: default
  - secrets: secrets
  - assetfitting: rot_and_aspect_weighted
  - scene: all_replica_scenes
  - parallelism: default